[package]
name = "monitor"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
sysinfo = "0.35.2"
actix-web = "4"
actix-rt = "2"
serde = { version = "1.0", features = ["derive"] }